language: node_js

matrix:
  fast_finish: true

node_js:
  - "10"
  - "12"
  - "node"

install:
  - node --version
  - npm --version --no-update-notifier
  - npm install --no-optional --no-save --no-update-notifier

script:
  - npm test --no-update-notifier

notifications:
  email: false