name: CI

on: [push, pull_request]

jobs:
  ci-latest:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ['*']
    name: CI - Node latest (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  ci:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: [12, 14, 16]
    name: CI - Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
